# Generated by Django 4.2.7 on 2024-02-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=255)),
                ('lname', models.TextField(max_length=255)),
                ('hname', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
