# Generated by Django 4.2.7 on 2024-02-25 20:04

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('id_document', models.ImageField(upload_to=app.models.document_upload_path)),
                ('healthcare_proxy', models.ImageField(upload_to=app.models.document_upload_path)),
                ('organ_donor_card', models.ImageField(upload_to=app.models.document_upload_path)),
            ],
        ),
    ]
