# Generated by Django 4.2.7 on 2024-02-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='full_name',
            new_name='name',
        ),
    ]
