# Generated by Django 4.2.7 on 2024-02-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_full_name_form_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='hospital_name',
            field=models.CharField(default='Default Hospital Name', max_length=255),
        ),
    ]
