# Generated by Django 4.2.7 on 2024-02-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_form_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='hospital_name',
            field=models.CharField(max_length=255),
        ),
    ]
