# Generated by Django 4.2.7 on 2024-02-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_form1'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='organ_name',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
    ]
