# Generated by Django 4.2.7 on 2024-02-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_form_organ_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='organ_name',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
