# Generated by Django 4.2.7 on 2024-02-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_form_organ_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='organ_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='organ_name',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
