# Generated by Django 4.2.7 on 2024-02-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_form1_organ_name_alter_form_organ_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='form1',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
