# Generated by Django 4.2.7 on 2024-03-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
