# Generated by Django 4.2.7 on 2024-03-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_file_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='email',
        ),
    ]
