# Generated by Django 4.2.7 on 2024-03-05 07:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_file_filedoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDoc1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=app.models.documents_upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='filedoc',
            name='file',
            field=models.ImageField(upload_to=app.models.documents_upload_path),
        ),
    ]
