# Generated by Django 4.2.7 on 2024-03-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_filedoc1_alter_filedoc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedoc',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filedoc1',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
