# Generated by Django 4.2.7 on 2024-03-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_filedoc_email_filedoc1_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedoc',
            name='email',
        ),
        migrations.RemoveField(
            model_name='filedoc1',
            name='email',
        ),
    ]
