# Generated by Django 4.2.7 on 2024-03-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_filedoc_email_remove_filedoc1_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedoc',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
