# Generated by Django 4.2.7 on 2024-04-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_filedoc_email_filedoc1_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='healthcare_proxy',
        ),
        migrations.RemoveField(
            model_name='form1',
            name='healthcare_proxy',
        ),
    ]
