# Generated by Django 4.2.7 on 2024-04-03 06:12

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_form_healthcare_proxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='healthcare_proxy',
            field=models.ImageField(default=1, upload_to=app.models.document_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form1',
            name='healthcare_proxy',
            field=models.ImageField(default=1, upload_to=app.models.document_upload_path),
            preserve_default=False,
        ),
    ]
