# Generated by Django 4.2.7 on 2024-04-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_form_healthcare_proxy_form1_healthcare_proxy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='healthcare_proxy',
            new_name='healthcare',
        ),
        migrations.RenameField(
            model_name='form1',
            old_name='healthcare_proxy',
            new_name='healthcare',
        ),
    ]
