# Generated by Django 4.2.7 on 2024-04-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_healthcare_proxy_form_healthcare_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='healthcare',
            new_name='healthcare_proxy',
        ),
        migrations.RenameField(
            model_name='form1',
            old_name='healthcare',
            new_name='healthcare_proxy',
        ),
    ]
