# Generated by Django 4.2.7 on 2024-04-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_healthcare_form_healthcare_proxy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='healthcare_proxy',
        ),
        migrations.RemoveField(
            model_name='form1',
            name='healthcare_proxy',
        ),
    ]
